### ISSUE TITLE
请问为什么我用自己的图片就会报错？

### ISSUE THREAD

**Issue by msute** [cs007888/numberRec#2]
同样是120*48的尺寸  也是png格式
![5EH@8ZR5@4Z1O DZKNX W9F](https://user-images.githubusercontent.com/52910627/70778946-6abd3d00-1dbe-11ea-9e64-f8546b346a8d.png)

**Comment by cs007888** [comment]
你好，我训练的这个模型图片尺寸是120*40的，你可以训练你自己的模型或者裁剪图片

**Comment by msute** [comment]
我裁剪了  我是四位数的验证码  他给我识别出
![image](https://user-images.githubusercontent.com/52910627/70782506-174cee00-1dc2-11ea-
89ea-07635f0eefc8.png)

可以加个qq请教一下吗

**Comment by cs007888** [comment]
wx: cs007888
